### ISSUE TITLE
How-to: Enum field

### ISSUE THREAD

**Issue by medikoo** [egovernment/egovernment.github.io#64]
We miss clear instruction on how to configure enum field. I believe we should just add it to "Define a field" how-to

**Comment by kamsi** [comment]
@mtuchowski you can view it here: http://help.eregistrations.org/how-to/define-a-new-field/

here is the relevant commit: https://github.com/egovernment/egovernment.github.io/commit/25bf9a014b652003d87135bb8b786365a0c44780

**Comment by mtuchowski** [comment]
Good.
