### ISSUE TITLE
How to: Document isApplicable for steps

### ISSUE THREAD

**Issue by medikoo** [egovernment/egovernment.github.io#66]
It should probably be in "Add new role(s)" we need a word on how to configure eventual applicablity rule for step

**Comment by kamsi** [comment]
@mtuchowski the overview: http://help.eregistrations.org/how-to/add-a-role/

commit: https://github.com/egovernment/egovernment.github.io/commit/b48a2fe8aedd32ffa3d65e3186177ddbfc4123a3

**Comment by mtuchowski** [comment]
Good.
