### ISSUE TITLE
How to: Add new institution

### ISSUE THREAD

**Issue by medikoo** [egovernment/egovernment.github.io#67]

**Comment by mtuchowski** [comment]
What `category` and `sub-category` should this be in? My guess would be `1. Part A` for category and possibly `Data` for the other. @medikoo @kamsi Any thoughts?

**Comment by medikoo** [comment]
Let's add it to "Other" (general) category

**Comment by mtuchowski** [comment]
@kamsi Ready to check http://help.eregistrations.org/how-to/add-new-institution/

**Comment by kamsi** [comment]
All good.
